### ISSUE TITLE
Where is the link of dataset?

### ISSUE THREAD

**Issue by gdut-cjy** [aimagelab/dress-code#1]

**Comment by marcellacornia** [comment]
As reported in the README file, the dataset will be available soon.

**Comment by kinivi** [comment]
HI @marcellacornia !

Are there any progress to see the public dataset ?

**Comment by marcellacornia** [comment]
Hi @kinivi! 

The dataset has been released more than three months ago, but can only be downloaded after filling in the [request form](https://forms.gle/72Bpeh48P7zQimin7) reported in the README file.
