### ISSUE TITLE
get Dataset 

### ISSUE THREAD

**Issue by rzzcl** [aimagelab/dress-code#13]
hi，marcellacornia，
I have already filled in the form in readme, but why haven't I received any feedback emails or download links?

**Comment by zhangtao22** [comment]
do you receive it？

**Comment by rzzcl** [comment]
> do you receive it？

I'm sorry, but I haven't received any response.

**Comment by omedivad** [comment]
I’m sorry, but we experienced severe server failure. The dataset is temporally not available. We will send the download link as soon as we are able to resolve the issue.

Thanks,

Davide

PhD Student
National PhD in Artificial Intelligence
University of Pisa
Email: ***@***.***
Email: ***@***.***
Twitter:https://twitter.com/omedivad
________________________________

**Comment by AItechnology** [comment]
I am very interested in this work, so I am looking forward to your replay about the datasets download link as soon as possible, thanks very much @omedivad

**Comment by songtao-liu-mt** [comment]
> I am very interested in this work, so I am looking forward to your replay about the datasets download link as soon as possible, thanks very much @omedivad

Is the dataset available now?

**Comment by omedivad** [comment]
Yes, the dataset is available.

To obtain it, you must request it using this[form](https://docs.google.com/forms/d/e/1FAIpQLSeWVzxWcj3JSALtthuw-2QDAbf2ymiK37sA4pRQD4tZz2vqsw/viewform).

Please make sure to fill all the fields in, use your institutional email, check the box for condition acceptance, and sign the document. For affiliation, we mean the university you work/study for. All the applications are manually reviewed for legal reasons, so if you don't get the dataset in one week, please check if you made any mistakes in the release agreement module and resubmit it.

If you still do not receive the dataset, please email me.

Davide

**Comment by ehsas01** [comment]
> Yes, the dataset is available.
> 
> To obtain it, you must request it using this[form](https://docs.google.com/forms/d/e/1FAIpQLSeWVzxWcj3JSALtthuw-2QDAbf2ymiK37sA4pRQD4tZz2vqsw/viewform).
> 
> Please make sure to fill all the fields in, use your institutional email, check the box for condition acceptance, and sign the document. For affiliation, we mean the university you work/study for. All the applications are manually reviewed for legal reasons, so if you don't get the dataset in one week, please check if you made any mistakes in the release agreement module and resubmit it.
> 
> If you still do not receive the dataset, please email me.
> 
> Davide

I fullfill the form(including my semnan_university_email), signed and sent it But without any reply!  Please check .Thanks.

**Comment by omedivad** [comment]
Hi @ehsas01,

we had some issues with the server hosting the dataset. 
Did you receive the download link?

Davide
