### ISSUE TITLE
[Colab Guide] Drive Link for Preprocessing pipeline of DressCode Dataset

### ISSUE THREAD

**Issue by kira1433** [aimagelab/dress-code#16]
I have made a Drive Link for generating pre-processing similar to the DressCode Dataset for any Custom Data. 
This will be useful for running inference on models which have been trained on DressCode dataset.

Please check this link out for more information  https://github.com/miccunifi/ladi-vton/issues/25#issue-1844828928

**Comment by TrongDuyNguyen0611** [comment]
I have no feedback on the Dress Code Dataset episode. Even though I sent the form and email to the author, there is still no response.

**Comment by chunxia75qin** [comment]
> I have no feedback on the Dress Code Dataset episode. Even though I sent the form and email to the author, there is still no response.

I have no feedback too, Did you get a reply now?

**Comment by omedivad** [comment]
I don't have unread emails in my inbox. 
Please double-check the email address you used in the request form, as I sometimes receive alerts for non-existing email addresses.

If you still haven't received the dataset, email me at my institutional email address.

Best,

Davide

**Comment by edith9922** [comment]
> I don't have unread emails in my inbox. Please double-check the email address you used in the request form, as I sometimes receive alerts for non-existing email addresses.
> 
> If you still haven't received the dataset, email me at my institutional email address.
> 
> Best,
> 
> Davide

hello. 
I'm not sure exactly which email you're referring to by institutional email, could you please write it down? 

All the best,
edith

**Comment by omedivad** [comment]
Write me at davide.morelli[at]unimore.it
