### ISSUE TITLE
no response after filling in the data form

### ISSUE THREAD

**Issue by Gal4way** [aimagelab/dress-code#18]
hi，Davide，
I have already filled in the form in readme, but I haven't received any feedback emails or download links?
Is the dataset still available?

**Comment by Jerome-Young** [comment]
I have also encountered a similar issue. May I ask if you have obtained the download link now?

> hi，Davide， I have already filled in the form in readme, but I haven't received any feedback emails or download links? Is the dataset still available?

**Comment by chunxia75qin** [comment]
> I have also encountered a similar issue. May I ask if you have obtained the download link now?
> 
> > hi，Davide， I have already filled in the form in readme, but I haven't received any feedback emails or download links? Is the dataset still available?

I have no feedback too, Did you get a reply now?

**Comment by omedivad** [comment]
Hi,

We manually review all the applications for legal reasons.

As stated in the request module:
1. we can release the dataset only to universities
2. An institutional email address must submit the request
3. You must submit the Release Agreement module, filling in every field and signing it with a handwritten signature

If you don't comply with all these requirements, we cannot release the dataset for legal reasons.

Please note that we manually review each application and receive many requests; we cannot explain why the dataset cannot be shared if you don't follow the guidelines.

If you think you are compliant with all the submission requirements and you don't receive the dataset link, write me an email and I'll personally check the status of your request.

Best,

Davide
