### ISSUE TITLE
Why even make a repo???

### ISSUE THREAD

**Issue by Hisairnessag3** [aimagelab/dress-code#19]
I don't care if you have a deal with a corporation. Don't make a repo if you aren't going to show the code from your paper. Your paper is not reproducible and therefore likely just hard coded(seeing as you have no upload clothing or model option).

Pathetic unscientific work.

**Comment by Hisairnessag3** [comment]
This is no better than Deepmind or OpenAI. Very sad

**Comment by marcellacornia** [comment]
Dear @Hisairnessag3, I think your comment does not deserve any response. However, we invite you to also refer to our subsequent works for which we have released the source code as we no longer have commercial constraints.

I wish you the best and good luck in your future research.

**Comment by omedivad** [comment]
Hi @Hisairnessag3,

If you believe this much in open source, you can fund a project of our research lab and provide us with data (not easy to find in our research domain).
We will release data, code, weights, and all you think is necessary.

You can write to our institutional emails for more details.
I look forward to hearing from you soon to start a collaboration.

Best,
Davide

**Comment by Hisairnessag3** [comment]
"I think your comment does not deserve any response."

Because you know no comment you would give would be satisfactory given the mission of science to advance collective knowledge. If you have commercial constraints(and therefore your "discovery" is not reproducible. DON'T WRITE A PAPER, DON'T MAKE A REPO. Keep your closed-source software closed-source. But don't feign as if you created something legitimately scientific. 

"If you believe this much in open source, you can fund a project of our research lab and provide us with data (not easy to find in our research domain)." 

Or you could work at a scientific institution if you want to publish research. Otherwise, keep your "research" to yourself, as all non-research institutions do.   

 "We will release data, code, weights, and all you think is necessary."

Sure, give me a date when your exclusivity contract ends so you can actually do what you pretend to do here.  Unfortunately, I'm not particularly eager to larp as if I am doing science so I do not see much collaboration in our future.
