### ISSUE TITLE
Missing segmentation label in `lower_body/label_maps/018112_4.png`

### ISSUE THREAD

**Issue by pierrot-lc** [aimagelab/dress-code#21]
Hi,

There is a skirt wrongly labeled as "upper body" in the segmentation map `lower_body/label_maps/018112_4.png`. I'm not sure if this is very relevant but I wanted to let you know.

Have a good day.

**Comment by pierrot-lc** [comment]
And there's actually the same issue with the segmentation map `upper_body/label_maps/010560_4.png`.

**Comment by omedivad** [comment]
Hi @pierrot-lc, many thanks for reporting the issue!

**Comment by pierrot-lc** [comment]
No problem :smile: feel free to mark the issue as closed if necessary.
