### ISSUE TITLE
Why I can't get your reply of dataset register

### ISSUE THREAD

**Issue by lyc0929** [aimagelab/dress-code#22]
I have finished the data request form

**Comment by omedivad** [comment]
Hi @lyc0929!

Did you receive the dataset download link?
If not, please write me to my institutional email address so I can check the status of your request.

Also, note that many requests we received did comply with the legal requirements:

- no institutional email address was provided
- the release agreement was not or only partially filled out
- institutions requiring the dataset were not university

These requests have been rejected.

**Comment by lyc0929** [comment]
> Hi @lyc0929!
> 
> Did you receive the dataset download link? If not, please write me to my institutional email address so I can check the status of your request.
> 
> Also, note that many requests we received did comply with the legal requirements:
> 
> * no institutional email address was provided
> * the release agreement was not or only partially filled out
> * institutions requiring the dataset were not university
> 
> These requests have been rejected.



I click the link and return error "
Forbidden
You don't have permission to access this resource."

**Comment by omedivad** [comment]
Hi @lyc0929, 

I tested the link, and it seems to work.
Could you try to download the dataset again and give me some feedback, please?
The issue can be due to the high number of downloads.

Davide
