### ISSUE TITLE
Not getting any response for  dataset request  

### ISSUE THREAD

**Issue by Mansu123** [aimagelab/dress-code#23]
I have request for the dataset for an emergency research work 5 days ago but didn't get any response yet...I have requested from this email mansuba.tabasssum.cse@ulab.edu.bd

**Comment by omedivad** [comment]
Hi @Mansu123,

We noticed you didn't tick the check box in the release agreement. 
In doing so, you didn't declare you understand and agree with all the requirements reported in the License, and for legal reasons, we cannot share the dataset with you.
Please tick the check box and submit your request again.

All the best,

Davide

**Comment by Mansu123** [comment]
Hey, I have fill out the form again by adding all  things , Can you please check it and Thanks for the response.

**Comment by omedivad** [comment]
Hi @Mansu123,

I sent you the link. You should be able to download the dataset now.

Davide
