### ISSUE TITLE
Are keypoints taken at different resolution? 

### ISSUE THREAD

**Issue by dawgster** [aimagelab/dress-code#4]
Hi! Thank you for your work on the dataset!
When doing some data exploration I encountered something peculiar.
When I visualize the skeleton defined by the openpose keypoints i get a scaled and offset skeleton relative to the image at 768x1024 resolution: 
[Image](https://imgur.com/gM7n4jD)
When I perform the visualization on images rescaled to 384x512 the skeleton aligns perfectly:
[Image](https://imgur.com/bokTbe6)

So my question is if the Keypoints were created using the 384x512 images and not the full resolution ones?

Kind Regards!

**Comment by omedivad** [comment]
Hi, happy you like our work!
Yes, we computed keypoints using 512x384 (HxW) resolution. 
If it could be useful, in the dataset folder there is also a readme.txt containing more information about the dataset.
Best regards!
