### ISSUE TITLE
Permisssion to access dataset request form

### ISSUE THREAD

**Issue by srckid** [aimagelab/dress-code#5]
Hi,
I'm very interested this project and want to use your dataset. 
But i can't access to the dataset request form link in readme
![image](https://user-images.githubusercontent.com/28746775/187352082-c0594844-a241-410a-8253-1760acfec62f.png)
Can you help me?
Thanks!

**Comment by omedivad** [comment]
Hi @srckid,
I think this issue could be related to your google account permissions.
Are you using your institutional google account? 
Could you try to access the form from another account?

**Comment by srckid** [comment]
> Hi @srckid, I think this issue could be related to your google account permissions. Are you using your institutional google account? Could you try to access the form from another account?

Done. The issue have fixed.
Thank for your reply!
