### ISSUE TITLE
Sir please do we get demo video to run this repository 

### ISSUE THREAD

**Issue by Deepak-D-Gowda** [aimagelab/dress-code#7]
Sir do we get video to run this repository , we are new here 

Please do reply.. we will be waiting for your reply
Thank you

**Comment by omedivad** [comment]
Hi @Deepak-D-Gowda,

the repo contains all the PyTorch code to load the dataset, but for legal reasons, we cannot share the model.

You should re-implement the model according to the paper.
Sorry but it's a pretty busy period, so I don't have time to make a how-to video right now.

Best.
