### ISSUE TITLE
Details around m

### ISSUE THREAD

**Issue by ifeherva** [aimagelab/dress-code#8]
Great work, thanks for sharing it.

I am trying to better understand the following part in the paper:

> to produce such masked
> representation, we use both the target label map to extract the clothes area and
> the pose map to extract the area of the limbs. These areas are then merged to
> form the mask which is then dilated to avoid the model getting information about
> the target shape. Finally, all the non-modifiable areas in the image (e.g. face,
> hands, hairs, etc.) are subtracted from the generated mask. The final mask is
> then applied to the image I.

- Were the masks for the limbs extracted from the densepose output?

- What was the dilation size?

Thank you!

**Comment by omedivad** [comment]
Thank you @ifeherva!

1. The masks for the limbs is extracted using the pose map.
2. The dilation changes accordingly to the image shape.

For more info, you can find the mask implementation in the code uploaded on GitHub, in:

[dress-code](https://github.com/aimagelab/dress-code)/[data](https://github.com/aimagelab/dress-code/tree/main/data)/dataset.py
